### ISSUE TITLE
Sort namespaces(Actions, Fields) by the order they appear in business class

### ISSUE THREAD

**Issue by clazarev** [bluemonkmn/lpl-outline#5]
The current  order is confusing as it is alphabetical. For example, Ontology shows  at the bottom of the outline.
Ideally, the outline should list namespaces in the order they exist in the business class, but at least it **would be nice** to see them sorted by BNF specification. That's how most of the classes are structured.

**Comment by bluemonkmn** [comment]
![image](https://user-images.githubusercontent.com/1648185/98245247-41f1e900-1f36-11eb-8c99-27d1b5ec2fd2.png)
