### ISSUE TITLE
Jump to definition window lists extended class files first

### ISSUE THREAD

**Issue by clazarev** [bluemonkmn/lpl-outline#6]
If I have an extended business class, i.g main file Test.busclass and Test.part1.busclass, Test.part2.busclass
when I click on the business class name **Test** in  the code to jump to definition, the windows lists all occurrences on the right but starts with 

- Test.part1.busclass
- Test.part2.busclass
- Test.busclass

etc, same for UI files

Expected: it makes sense to list secondary files after the main files

**Comment by bluemonkmn** [comment]
The sorting appears to be built into VS Code. Changing the sort order of the items given to VS code had no effect on the order in which VS code presented them. There doesn't appear to be any way to control the order from the extension.
